interpolator_isotherm.o: interpolator_isotherm.hpp interpolator_isotherm.cpp
	g++ interpolator_isotherm.cpp -c -std=c++11 -O3

solver_factory.o: solver_factory.hpp solver_factory.cpp
	g++ solver_factory.cpp -c -std=c++11 -O3

linear_interpolator.o: linear_interpolator.hpp linear_interpolator.cpp
	g++ linear_interpolator.cpp -c -std=c++11 -O3

bisection_solver.o: bisection_solver.hpp bisection_solver.cpp
	g++ bisection_solver.cpp -c -std=c++11 -O3

arma_solver.o: arma_solver.hpp arma_solver.cpp
	g++ arma_solver.cpp -c -std=c++11 -O3 ${ARMA_IMPORT}

simplex_solver.o: simplex_solver.hpp simplex_solver.cpp
	g++ simplex_solver.cpp -c -std=c++11 -O3

simplex.o: simplex.hpp simplex.cpp
	g++ simplex.cpp -c -std=c++11 -O3
